trigger:
- main

pool:
  vmImage: windows-latest


steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

# Separating this ensures clean dependency tracking
- script: |
    npm ci
  displayName: 'Install Dependencies (npm ci)'

# Isolating the build ensures it actually runs completely before moving forward
- script: |
    npm run build -- --configuration production
  displayName: 'Build Angular Application'

- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    # Your angular.json maps perfectly to this path
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/dist/browser'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure subscription 1(1)(625ce2b7-370d-4af7-9bee-bcceae4ca23b)'
    appType: 'webApp'
    appName: 'webappangular'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    deploymentMethod: 'auto'